apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

configMapGenerator:
  - name: env
    behavior: merge
    literals:
      - ENVIRONMENT=staging

patchesStrategicMerge:
  - |
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: vs
    spec:
      hosts:
        - ms-test-app.k8s.eu-west-1.non-prod.busuu.net
